; pokedex ids
; indexes for:
; - BaseStats (see data/pokemon/base_stats.asm)
; - MonPartyData (see data/pokemon/menu_icons.asm)
; - MonsterPalettes (see data/pokemon/palettes.asm)
	const_def 1
	const DEX_BULBASAUR  ; 1
	const DEX_IVYSAUR    ; 2
	const DEX_VENUSAUR   ; 3
	const DEX_CHARMANDER ; 4
	const DEX_CHARMELEON ; 5
	const DEX_CHARIZARD  ; 6
	const DEX_SQUIRTLE   ; 7
	const DEX_WARTORTLE  ; 8
	const DEX_BLASTOISE  ; 9
	const DEX_CATERPIE   ; 10
	const DEX_METAPOD    ; 11
	const DEX_BUTTERFREE ; 12
	const DEX_WEEDLE     ; 13
	const DEX_KAKUNA     ; 14
	const DEX_BEEDRILL   ; 15
	const DEX_PIDGEY     ; 16
	const DEX_PIDGEOTTO  ; 17
	const DEX_PIDGEOT    ; 18
	const DEX_RATTATA    ; 19
	const DEX_RATICATE   ; 20
	const DEX_SPEAROW    ; 21
	const DEX_FEAROW     ; 22
	const DEX_EKANS      ; 23
	const DEX_ARBOK      ; 24
	const DEX_PIKACHU    ; 25
	const DEX_RAICHU     ; 26
	const DEX_SANDSHREW  ; 27
	const DEX_SANDSLASH  ; 28
	const DEX_NIDORAN_F  ; 29
	const DEX_NIDORINA   ; 30
	const DEX_NIDOQUEEN  ; 31
	const DEX_NIDORAN_M  ; 32
	const DEX_NIDORINO   ; 33
	const DEX_NIDOKING   ; 34
	const DEX_CLEFAIRY   ; 35
	const DEX_CLEFABLE   ; 36
	const DEX_VULPIX     ; 37
	const DEX_NINETALES  ; 38
	const DEX_JIGGLYPUFF ; 39
	const DEX_WIGGLYTUFF ; 40
	const DEX_ZUBAT      ; 41
	const DEX_GOLBAT     ; 42
	const DEX_CROBAT     ; 43
	const DEX_TOGEPI     ; 44
	const DEX_TOGETIC    ; 45
	const DEX_TOGEKISS   ; 46
	const DEX_ODDISH     ; 47
	const DEX_GLOOM      ; 48
	const DEX_VILEPLUME  ; 49
	const DEX_BELLOSSOM  ; 50
	const DEX_MARILL     ; 51
	const DEX_AZUMARILL  ; 52
	const DEX_PARAS      ; 53
	const DEX_PARASECT   ; 54
	const DEX_VENONAT    ; 55
	const DEX_VENOMOTH   ; 56
	const DEX_DIGLETT    ; 57
	const DEX_DUGTRIO    ; 58
	const DEX_MEOWTH     ; 59
	const DEX_PERSIAN    ; 60
	const DEX_PSYDUCK    ; 61
	const DEX_GOLDUCK    ; 62
	const DEX_MANKEY     ; 63
	const DEX_PRIMEAPE   ; 64
	const DEX_GROWLITHE  ; 65
	const DEX_ARCANINE   ; 66
	const DEX_SUDOWOODO  ; 67
	const DEX_POLIWAG    ; 68
	const DEX_POLIWHIRL  ; 69
	const DEX_POLIWRATH  ; 70
	const DEX_POLITOED   ; 71
	const DEX_AIPOM      ; 72
	const DEX_AMBIPOM    ; 73
	const DEX_ABRA       ; 74
	const DEX_KADABRA    ; 75
	const DEX_ALAKAZAM   ; 76
	const DEX_MACHOP     ; 77
	const DEX_MACHOKE    ; 78
	const DEX_MACHAMP    ; 79
	const DEX_YANMA      ; 80
	const DEX_YANMEGA    ; 81
	const DEX_BELLSPROUT ; 82
	const DEX_WEEPINBELL ; 83
	const DEX_VICTREEBEL ; 84
	const DEX_TENTACOOL  ; 85
	const DEX_TENTACRUEL ; 86
	const DEX_GEODUDE    ; 87
	const DEX_GRAVELER   ; 88
	const DEX_GOLEM      ; 89
	const DEX_PONYTA     ; 90
	const DEX_RAPIDASH   ; 91
	const DEX_MURKROW    ; 92
	const DEX_HONCHKROW  ; 93
	const DEX_SLOWPOKE   ; 94
	const DEX_SLOWBRO    ; 95
	const DEX_SLOWKING   ; 96
	const DEX_MISDREAVUS ; 97
	const DEX_MISMAGIUS  ; 98
	const DEX_MAGNEMITE  ; 99
	const DEX_MAGNETON   ; 100
	const DEX_MAGNEZONE  ; 101
	const DEX_FARFETCHD  ; 102
	const DEX_DODUO      ; 103
	const DEX_DODRIO     ; 104
	const DEX_SEEL       ; 105
	const DEX_DEWGONG    ; 106
	const DEX_GRIMER     ; 107
	const DEX_MUK        ; 108
	const DEX_SHELLDER   ; 109
	const DEX_CLOYSTER   ; 110
	const DEX_GASTLY     ; 111
	const DEX_HAUNTER    ; 112
	const DEX_GENGAR     ; 113
	const DEX_GLIGAR     ; 114
	const DEX_GLISCOR    ; 115
	const DEX_ONIX       ; 116
	const DEX_STEELIX    ; 117
	const DEX_DROWZEE    ; 118
	const DEX_HYPNO      ; 119
	const DEX_KRABBY     ; 120
	const DEX_KINGLER    ; 121
	const DEX_VOLTORB    ; 122
	const DEX_ELECTRODE  ; 123
	const DEX_EXEGGCUTE  ; 124
	const DEX_EXEGGUTOR  ; 125
	const DEX_CUBONE     ; 126
	const DEX_MAROWAK    ; 127
	const DEX_HITMONLEE  ; 128
	const DEX_HITMONCHAN ; 129
	const DEX_HITMONTOP  ; 130
	const DEX_LICKITUNG  ; 131
	const DEX_LICKILICKY ; 132
	const DEX_KOFFING    ; 133
	const DEX_WEEZING    ; 134
	const DEX_RHYHORN    ; 135
	const DEX_RHYDON     ; 136
	const DEX_RHYPERIOR  ; 137
	const DEX_CHANSEY    ; 138
	const DEX_BLISSEY    ; 139
	const DEX_TANGELA    ; 140
	const DEX_TANGROWTH  ; 141
	const DEX_KANGASKHAN ; 142
	const DEX_SNEASEL    ; 143
	const DEX_WEAVILE    ; 144
	const DEX_SLUGMA     ; 145
	const DEX_MAGCARGO   ; 146
	const DEX_SWINUB     ; 147
	const DEX_PILOSWINE  ; 148
	const DEX_MAMOSWINE  ; 149
	const DEX_HOUNDOUR   ; 150
	const DEX_HOUNDOOM   ; 151
	const DEX_HORSEA     ; 152
	const DEX_SEADRA     ; 153
	const DEX_KINGDRA    ; 154
	const DEX_GOLDEEN    ; 155
	const DEX_SEAKING    ; 156
	const DEX_STARYU     ; 157
	const DEX_STARMIE    ; 158
	const DEX_MR_MIME    ; 159
	const DEX_SCYTHER    ; 160
	const DEX_SCIZOR     ; 161
	const DEX_JYNX       ; 162
	const DEX_ELECTABUZZ ; 163
	const DEX_ELECTIVIRE ; 164
	const DEX_MAGMAR     ; 165
	const DEX_MAGMORTAR  ; 166
	const DEX_PINSIR     ; 167
	const DEX_TAUROS     ; 168
	const DEX_MAGIKARP   ; 169
	const DEX_GYARADOS   ; 170
	const DEX_LAPRAS     ; 171
	const DEX_DITTO      ; 172
	const DEX_EEVEE      ; 173
	const DEX_VAPOREON   ; 174
	const DEX_JOLTEON    ; 175
	const DEX_FLAREON    ; 176
	const DEX_ESPEON     ; 177
	const DEX_UMBREON    ; 178
	const DEX_LEAFEON    ; 179
	const DEX_GLACEON    ; 180
	const DEX_SYLVEON    ; 181
	const DEX_PORYGON    ; 182
	const DEX_PORYGON2   ; 183
	const DEX_PORYGON_Z  ; 184
	const DEX_OMANYTE    ; 185
	const DEX_OMASTAR    ; 186
	const DEX_KABUTO     ; 187
	const DEX_KABUTOPS   ; 188
	const DEX_AERODACTYL ; 189
	const DEX_SNORLAX    ; 190
	const DEX_ARTICUNO   ; 191
	const DEX_ZAPDOS     ; 192
	const DEX_MOLTRES    ; 193
	const DEX_DRATINI    ; 194
	const DEX_DRAGONAIR  ; 195
	const DEX_DRAGONITE  ; 196
	const DEX_LARVITAR   ; 197
	const DEX_PUPITAR    ; 198
	const DEX_TYRANITAR  ; 199
	const DEX_MEWTWO     ; 200
	const DEX_MEW        ; 201

DEF NUM_POKEMON EQU const_value - 1
